### ISSUE TITLE
Polish locale

### ISSUE THREAD

**Issue by sjzurek** [ryanstreet/magento2-vagrant#12]
I was surprised that apart from en_US there is pl_PL.
Any reason?
I don't mind it there, just curious (as being Polish my self)

**Comment by ryanstreet** [comment]
Not sure where you mean.  I don't have the polish locale as part of my default.  Interesting...

**Comment by ryanstreet** [comment]
https://crowdin.com/project/magento-2

Polish is about 76% translated.  Please feel free to contribute to the project!  We could all use your help :)
