### ISSUE TITLE
Composer not working

### ISSUE THREAD

**Issue by rickoconnor** [ryanstreet/magento2-vagrant#13]
After going through all the steps:

Autoload error

Vendor autoload is not found. Please run 'composer install' under application root directory.

**Comment by piper-at-dawn** [comment]
@rickoconnor What I did was this:

vagrant ssh --- to log into the running server
cd /vagrant/magento2
composer install
this should run through all the installs (probably ask you for your git personal access code) and once installed I was able to hit the url just fine and finish the install.

Hope this helps!

**Comment by rickoconnor** [comment]
That worked!  Thanks!

**Comment by ryanstreet** [comment]
Thanks @piper-at-dawn !
